language: node_js
node_js:
  - "12"

cache:
  yarn: true

notifications:
  email: false

# update yarn to the newest version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn workspaces run test-ci --ci
