language: node_js
node_js:
  - "12"

cache:
  yarn: true

notifications:
  email: false

# update yarn to the newest version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn workspace @timeflies/shared build
  - yarn workspaces run test-ci --ci
  - yarn workspace @timeflies/back build
  - yarn workspace @timeflies/front build
