compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@storybook/addons@*":
    dependencies:
      "@types/webpack-env": "*"
  "@storybook/react@*":
    dependencies:
      "@storybook/client-api": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-import-resolver-node@*:
    dependencies:
      resolve: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eslint-plugin-import@*:
    dependencies:
      eslint-import-resolver-node: "*"
  react-pixi-fiber@*:
    dependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
