plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

# TODO remove these lines after deps are fixed
pnpMode: loose
# pnpFallbackMode: all

packageExtensions:
#   eslint-module-utils@*:
#     dependencies:
#       eslint-import-resolver-node: "*"
  eslint-plugin-import@*:
    dependencies:
      eslint-import-resolver-node: "*" 
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eslint-import-resolver-node@*:
    dependencies:
      resolve: "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  "@storybook/addons@*":
    dependencies:
      "@types/webpack-env": "*"
  "@storybook/react@*":
    dependencies:
      "@storybook/client-api": "*"
  debug@*:
    dependencies:
      supports-color: "*"
