packageExtensions:
  "@storybook/addons@*":
    dependencies:
      "@types/webpack-env": "*"
  "@storybook/react@*":
    dependencies:
      "@storybook/client-api": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-import-resolver-node@*:
    dependencies:
      resolve: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eslint-plugin-import@*:
    dependencies:
      eslint-import-resolver-node: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-berry.cjs
