#!/bin/bash

# Netlify does not handle .yarnrc.yml directly, so we have to create a .yarnrc with yarn2 path

function generateOlgYarnrc {

    local oldYarnrcPath='.yarnrc'

    local yarnPath=$(grep -oP '(?<=yarnPath: ).*' $1)

    echo '# AUTOGENERATED FILE - DO NOT EDIT
# Used by Netlify which does not handle .yarnrc.yml directly.

# lastUpdateCheck '$(date +%s%N)'
yarn-path "'$yarnPath'"' > $oldYarnrcPath
}

generateOlgYarnrc .yarnrc.yml
