
name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build shared
      run: yarn workspace @timeflies/shared build

    - name: Run benchmark
      run: cd packages/front && yarn check-performance
      env:
        CI: true

    # Download previous benchmark result from cache (if exists)
    - name: Download previous benchmark data
      uses: actions/cache@v2
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1.8.1
      with:
        name: Benchmark.js Benchmark
        tool: 'benchmarkjs'

        # Where the previous data file is stored
        external-data-json-path: ./cache/benchmark-data.json

        output-file-path: packages/front/benchmark/temp/results.txt

        github-token: ${{ secrets.GITHUB_TOKEN }}

        comment-on-alert: true
        alert-threshold: '150%'
        fail-on-alert: true
