
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare-cache:
    name: Prepare Cache
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Check Yarn dedupe
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn dedupe --check

      - name: Check or update Yarn cache
        run: |
          yarn install --immutable --skip-builds

      - id: set-matrix
        run: echo "::set-output name=matrix::$(yarn node ./scripts/get-ci-packages.js)"

  # prepare-matrix:
  #   needs: prepare-cache
  #   name: Prepare CI matrix
  #   runs-on: ubuntu-18.04
  #   # outputs:
  #   #   matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Use Node.js latest
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
  #     - uses: actions/cache@v2
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: yarn-${{ hashFiles('yarn.lock') }}
  #     - name: Install
  #       run: yarn install
  #     - id: set-matrix
  #       # run: yarn foo
  #       run: echo "::set-output name=matrix::$(yarn node ./scripts/get-ci-packages.js)"

  checks:
    needs: prepare-cache
    runs-on: ubuntu-18.04

    strategy:
      matrix: ${{fromJson(needs.prepare-cache.outputs.matrix)}}

    name: ${{ matrix.package }} - Checks

    steps:
    # - name: Get yarn cache directory path
    #   id: yarn-cache-dir-path
    #   run: echo "::set-output name=dir::$(yarn cache dir)"

    # - uses: actions/cache@v2
    #   id: yarn-cache
    #   with:
    #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
    #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-yarn-

    - name: Check type + lint + dependencies
      run: cd ${{ matrix.package }} && yarn p:check-all
      env:
        CI: true
      
  # test:
  #   name: Test
  #   runs-on: ubuntu-18.04

  #   strategy:
  #     matrix:
  #       node-version: [12.x]

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Use node ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}

  #   - name: Get yarn cache directory path
  #     id: yarn-cache-dir-path
  #     run: echo "::set-output name=dir::$(yarn cache dir)"

  #   - uses: actions/cache@v2
  #     id: yarn-cache
  #     with:
  #       path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #       key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-yarn-

  #   - name: Install dependencies
  #     run: yarn --frozen-lockfile

  #   - name: Build devtools
  #     run: yarn workspace @timeflies/devtools build

  #   - name: Build common
  #     run: yarn workspace @timeflies/common build

  #   - name: Build shared
  #     run: yarn workspace @timeflies/shared build

  #   - name: Test all
  #     run: yarn workspaces run test-ci --ci
  #     env:
  #       CI: true

  # build:
  #   name: Build
  #   runs-on: ubuntu-18.04

  #   strategy:
  #     matrix:
  #       node-version: [12.x]

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Use node ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}

  #   - name: Get yarn cache directory path
  #     id: yarn-cache-dir-path
  #     run: echo "::set-output name=dir::$(yarn cache dir)"

  #   - uses: actions/cache@v2
  #     id: yarn-cache
  #     with:
  #       path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #       key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-yarn-

  #   - name: Install dependencies
  #     run: yarn --frozen-lockfile

  #   - name: Build shared
  #     run: yarn workspace @timeflies/shared build

  #   - name: Build backend
  #     run: yarn workspace @timeflies/back build

  #   - name: Build frontend
  #     run: yarn workspace @timeflies/front build
