
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  prepare-cache:
    name: Prepare Cache
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Check Yarn dedupe
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn dedupe --check

      - name: Check or update Yarn cache
        run: |
          yarn install --immutable --skip-builds

      - name: Set Matrix packages
        id: set-matrix
        run: echo "::set-output name=matrix::$(yarn node ./scripts/get-ci-packages.js)"

  checks:
    needs: prepare-cache
    runs-on: ubuntu-18.04

    strategy:
      matrix: ${{fromJson(needs.prepare-cache.outputs.matrix)}}

    name: ${{ matrix.package.name }} - Checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies (cache)
        run: yarn install --immutable --skip-builds

      - name: Build recursive
        run: cd ${{ matrix.package.path }} && yarn p:build-recursive

      - name: Test
        run: cd ${{ matrix.package.path }} && yarn p:test-ci

      - name: Check lint
        run: cd ${{ matrix.package.path }} && yarn p:check-lint

      - name: Check dependencies
        run: cd ${{ matrix.package.path }} && yarn p:check-deps
